apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker
  labels:
    app: {{ .Release.Name }}-worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-worker
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          command: ["node", "src/workers/cronWorker.js"]
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-secrets
          env:
            - name: NODE_ENV
              value: {{ .Values.global.environment }}
            - name: DB_HOST
              value: {{ .Values.backend.env.DB_HOST }}
            - name: DB_NAME
              value: {{ .Values.backend.env.DB_NAME }}
            - name: REDIS_HOST
              value: {{ .Values.backend.env.REDIS_HOST }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
