groups:
  - name: stock-system-alerts
    rules:
      # 1. Disponibilidad del Servicio
      - alert: BackendServiceDown
        expr: up{job="otel-collector"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Servidor Backend caido"
          description: "La instancia {{ $labels.instance }} del job {{ $labels.job }} está caída."

      # 2. Latencia Alta (> 500ms)
      - alert: HighLatency
        expr: rate(http_server_duration_sum[5m]) / rate(http_server_duration_count[5m]) > 0.5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Latencia alta detectada"
          description: "La latencia promedio es superior a 500ms en los últimos 2 minutos."

      # 3. Tasa de Errores Crítica (> 5% errores 5xx)
      - alert: HighErrorRate
        expr: (sum by(instance) (rate(http_server_duration_count{status_code=~"5.."}[5m]))) / (sum by(instance) (rate(http_server_duration_count[5m]))) > 0.05
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Tasa de errores 5xx superior al 5%"
          description: "Se detectó una tasa de errores críticos mayor al 5% en la instancia {{ $labels.instance }}."

      # 4. Fallos de Readiness
      - alert: ModuleNotReady
        expr: http_response_status_code{path=~".*/ready"} != 200
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Módulo no está listo (Readiness Check fallido)"
          description: "El endpoint {{ $labels.path }} está reportando fallos de salud."
