apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  DB_USER: {{ .Values.secrets.dbUser }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret }}
  MELI_ACCESS_TOKEN: {{ .Values.secrets.meliAccessToken }}
  GOOGLE_CLIENT_ID: {{ .Values.secrets.googleClientId }}
  MS_CLIENT_ID: {{ .Values.secrets.msClientId }}
